language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.4
    - nightly
env:
    - TEST_GROUP="basic"
    - TEST_GROUP="combined"
    - TEST_GROUP="groupmisc"
notifications:
    email: false
sudo: false
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # build tagged releases
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --optimize=0 --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';
jobs:
  allow_failures:
    - julia: nightly
  # include:
  #   - stage: "Documentation"
  #     julia: 1.4
  #     os: linux
  #     script:
  #       - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
  #       - julia --project=docs/ docs/make.jl
  #     after_success: skip
after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
