[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
HybridArrays = "1baab800-613f-4b0a-84e4-9cd3431bfbb9"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BoundaryValueDiffEq = "4, 5"
CSV = "0.10"
DataFrames = "1"
Distributions = "0.22.6, 0.23, 0.24, 0.25"
HybridArrays = "0.4"
IJulia = "1"
Manifolds = "0.10"
ManifoldsBase = "1"
MultivariateStats = "0.10"
RecursiveArrayTools = "3"
StaticArrays = "1"
