name: Documenter
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'preview docs') || github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.551"
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.10"
      - name: Julia Cache
        uses: julia-actions/cache@v2
      - name: Cache Quarto
        id: cache-quarto
        uses: actions/cache@v4
        env:
          cache-name: cache-quarto
        with:
          path: tutorials/_freeze
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('tutorials/*.qmd') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Cache Documenter
        id: cache-documenter
        uses: actions/cache@v4
        env:
          cache-name: cache-documenter
        with:
          path: docs/src/tutorials
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('tutorials/*.qmd') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Cache CondaPkg
        id: cache-condaPkg
        uses: actions/cache@v4
        env:
          cache-name: cache-condapkg
        with:
          path: docs/.CondaPkg
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('docs/CondaPkg.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: "Documenter rendering (including Quarto)"
        run: "docs/make.jl --quarto"
        env:
          PYTHON: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
  note:
    name: "Documentation deployment note."
    runs-on: ubuntu-latest
    if: "!contains( github.event.pull_request.labels.*.name, 'preview docs')"
    steps:
      - name: echo instructions
        run: echo 'The Documentation is only generated and pushed on a PR if the “preview docs” label is added.'
